### PR TITLE
Misc improvements to parser

### PR DESCRIPTION
**Pull request by federicobond**
Each commit message explains the change.

These have all been tested against a [sizeable spec](https://github.com/federicobond/solidity-spec), so they shouldn't introduce any regressions.

### CODE REVIEW

**Comment by raineorshine** [comment]
Fails to parse an `AssignmentExpression` in `SourceElement`:

```
pragma solidity ^0.4.4;

contract MyContract {
  bool locked = false;
}
```

**Comment by federicobond** [comment]
Hi Raine, thanks for testing and reporting. I fixed the problem in the last commit.

**Comment by tcoulter** [comment]
@federicobond This looks good. Do these improvements add features to what can be parsed, or is it a general grammar reorganization / cleanup? If features are added (such as "we can now parse `x`", where x is some new expression or construct) then please add that construct to https://github.com/ConsenSys/solidity-parser/blob/master/test/doc_examples.sol so the tests will catch it.

**Comment by tcoulter** [comment]
Otherwise @federicobond, great work and glad to have you working on this.

**Comment by federicobond** [comment]
Updated tests and rebuilt parser.

**Pull request merged**
