### PR TITLE
Add support for solidity interfaces

### LINKED ISSUE #67: Support for Interfaces
With new version of solidity (0.4.11) we have now support for interfaces.

Currently if you add following code to contract source:
```
interface i {
  function f();
}
```

Parser will fail to parse it. E.g if you add this code to solidity parser tests it will result in following error:
```
     Expected "contract", "import", "library", "pragma", comment, end of input, end of line, or whitespace but "i" found. Line: 19, Column: 1
  SyntaxError: Expected "contract", "import", "library", "pragma", comment, end of input, end of line, or whitespace but "i" found.
      at peg$buildStructuredError (build/parser.js:1272:12)
      at Object.peg$parse [as parse] (build/parser.js:13877:11)
      at Object.parse (index.js:34:23)
      at Object.parseFile (index.js:45:17)
      at Context.<anonymous> (test/general.js:15:20)
```

This makes it impossible to use interfaces with Truffle.

### PR DESCRIPTION
**Pull request by marekkirejczyk**
Fixes #67

### CODE REVIEW

**Comment by federicobond** [comment]
Thanks Marek! Can we change the node type from ContractStatement to InterfaceStatement before merging?

@tcoulter we should should probably update all three of these rules (library/contract/interface) to emit a node that has always ContractDefinition as type and a key named "kind" that takes either "contract", "library" or "interface" as value, but that would be a breaking change. What do you think?

**Comment by marekkirejczyk** [comment]
@federicobond done.

**Comment by federicobond** [comment]
Thank you! 🙌

**Comment by ngan** [comment]
Hi, just wondering when this will be released?

**Pull request merged**
