### PR TITLE
Update PEG.js dependency

### PR DESCRIPTION
**Pull request by federicobond**

### CODE REVIEW

**Comment by tcoulter** [comment]
Do we know if this upgrade affects the output or structure of the AST? We don't have great tests for that, admittedly.

**Comment by tcoulter** [comment]
Very happy to have this upgrade, and thank you @federicobond. Want to double check the above before merging.

**Comment by federicobond** [comment]
I checked the full changelog for the latest release of PEG.js, and found no
user-visible changes.

I can diff the output against my whole spec if you want though.

**Comment by tcoulter** [comment]
Nope, sounds good. Thanks @federicobond!

**Pull request merged**
